.build:docker_image:
  stage: build
  image: docker:20.10
  tags: [dot-2highcpu-n2]
  variables:
    DOT_DOCKERHUB_REPO: ${DOT_DOCKERHUB_USERNAME}/playground.boilerplates.${CI_PROJECT_NAME}
  before_script:
    - echo ${DOT_DOCKERHUB_PASSWORD} | docker login -u ${DOT_DOCKERHUB_USERNAME} --password-stdin
  script:
    - cp $DOTENV_FILE_PATH .env.local
    - docker build
      --progress plain
      --tag ${DOT_DOCKERHUB_REPO}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
      --tag ${DOT_DOCKERHUB_REPO}:${CI_COMMIT_BRANCH}
      .
    - docker push ${DOT_DOCKERHUB_REPO}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
    - docker push ${DOT_DOCKERHUB_REPO}:${CI_COMMIT_BRANCH}

build_develop:docker_image:
  extends: .build:docker_image
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  variables:
    DOTENV_FILE_PATH: $DOTENV_DEVELOP

deploy_develop:docker:
  stage: deploy
  image: asia.gcr.io/dot-gitlab-runner/ansible:2.9.21
  tags: [dot]
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  environment:
    name: develop
    url: https://nextjs-admiral-blrplt.dot.co.id
  before_script:
    - chmod 600 $ANSIBLE_KEY_FILE
    - ansible-galaxy collection install community.docker:==3.4.0
  script:
    - ansible-playbook --private-key $ANSIBLE_KEY_FILE -i deploy/ansible/hosts -v deploy/ansible/${CI_COMMIT_BRANCH}.yaml
